import { formatCurrency, formatDateTime } from "@/lib/format";
import type { PaymentMethod } from "@/lib/types";
import type { ReportBranding } from "@/modules/reports/core/report-context";
import { amountInArabicWords } from "@/modules/print-engine/lib/amount-in-words-ar";

const PAYMENT_LABELS: Record<"ar" | "en", Record<PaymentMethod, string>> = {
  ar: { cash: "نقدي", card: "بطاقة", wallet: "محفظة", credit: "آجل", other: "أخرى" },
  en: { cash: "Cash", card: "Card", wallet: "Wallet", credit: "Credit", other: "Other" },
};

export type ReceiptDocumentViewProps = {
  title: string; number: string; date: string; amount: number; branding: ReportBranding;
  partyLabel: string; partyName?: string | null; paymentStatus?: "paid" | "unpaid" | "partial" | null;
  payments?: Array<{ id: string; method: PaymentMethod; amount: number }>;
  details?: Array<{ label: string; value: string }>;
  notes?: string | null; isDraft?: boolean;
  items?: Array<{ id: string; name: string; quantity: number; unitPrice: number; total: number }>;
  summary?: Array<{ label: string; value: string; strong?: boolean }>;
  language?: "ar" | "en";
};

export function ReceiptDocumentView({ title, number, date, amount, branding, partyLabel, partyName, paymentStatus, payments = [], details = [], notes, isDraft, items = [], summary = [], language = "ar" }: ReceiptDocumentViewProps) {
  const ar = language === "ar";
  const paidInFull = paymentStatus === "paid";
  const rows = [
    ...payments.map((payment, index) => ({ label: index ? `${ar ? "طريقة الدفع" : "Payment method"} ${index + 1}` : ar ? "طريقة الدفع" : "Payment method", value: `${PAYMENT_LABELS[language][payment.method]} — ${formatCurrency(payment.amount, branding.currency)}` })),
    ...details,
  ];
  return <article data-print-root data-print-variant="executive" data-print-document="receipt" dir={ar ? "rtl" : "ltr"} className="velora-print-page receipt-page" style={{ "--print-primary": "#0f172a", "--print-accent": "#3b82f6", "--print-text": "#0f172a", "--print-muted": "#64748b", "--print-border": "#dbe3ef" } as React.CSSProperties}>
    <header className="print-header"><div className="print-company"><div className="print-wordmark">{branding.orgName || "VELORA"}<span>.</span></div><div className="print-company__details">{branding.storeName ? <p>{branding.storeName}</p> : null}{branding.storeAddress ? <p>{branding.storeAddress}</p> : null}{branding.storePhone ? <p dir="ltr">{branding.storePhone}</p> : null}</div></div><div className="print-identity"><h1>{title}</h1><p className="print-document-number">#{number.replace(/^#/, "")}</p><p>{formatDateTime(date)}</p>{isDraft ? <p>{ar ? "مسودة — غير نهائية" : "Draft — not final"}</p> : null}</div></header>
    <section className="receipt-party"><p className="print-eyebrow">{partyLabel}</p><h2>{partyName || "—"}</h2></section>
    <section className="receipt-amount"><p className="print-eyebrow">{ar ? "المبلغ" : "Amount"}</p><strong>{formatCurrency(amount, branding.currency)}</strong>{ar ? <p>{amountInArabicWords(amount)}</p> : null}</section>
    {rows.length ? <section className="receipt-details"><p className="print-eyebrow">{ar ? "تفاصيل الدفع" : "Payment details"}</p><dl>{rows.map((row) => <div key={`${row.label}-${row.value}`}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl></section> : null}
    {items.length ? <table className="print-lines receipt-items"><thead><tr><th>{ar ? "البيان" : "Item"}</th><th>{ar ? "الكمية" : "Qty"}</th><th>{ar ? "السعر" : "Price"}</th><th>{ar ? "الإجمالي" : "Total"}</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.name}</strong></td><td>{item.quantity}</td><td>{formatCurrency(item.unitPrice, branding.currency)}</td><td><strong>{formatCurrency(item.total, branding.currency)}</strong></td></tr>)}</tbody></table> : null}
    {summary.length ? <section className="receipt-summary">{summary.map((row) => <p key={row.label} className={row.strong ? "receipt-summary__strong" : undefined}><span>{row.label}</span><strong>{row.value}</strong></p>)}</section> : null}
    {paidInFull ? <p className="receipt-paid">{ar ? "مدفوع بالكامل" : "Paid in full"}</p> : null}
    {notes ? <section className="receipt-notes"><p className="print-eyebrow">{ar ? "ملاحظات" : "Notes"}</p><p>{notes}</p></section> : null}
    <section className="print-signatures"><div><span />{ar ? "إعداد" : "Prepared by"}</div><div><span />{ar ? "العميل / المستلم" : "Customer / Recipient"}</div></section>
    <footer className="print-footer"><span>{branding.receiptFooter || branding.storeName || "Velora"}</span><span>Generated by Velora</span><span>1 / 1</span></footer>
  </article>;
}
